<?php

use Krystal\Form\Element;
use Krystal\Widget\GridView\GridViewWidget;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="btn-toolbar">
    <?php $this->loadPartial('menu', array(
        'items' => array(
            'Faq:Admin:Faq@addAction' => 'Add new FAQ',
            'Faq:Admin:Category@addAction' => 'Add a category',
        ),
        'actions' => array(
            'data' => $faqs,
            'save' => 'Faq:Admin:Faq@tweakAction',
            'delete' => 'Faq:Admin:Faq@deleteAction'
        )
    )); ?>
</div>

<div class="card">
    <form>
        <?php $this->loadPartial('items-per-page', array('caption' => 'FAQ')); ?>

        <?= $this->widget(new GridViewWidget($faqs, array(
            'batch' => true,
            'pk' => 'id',
            'tableClass' => 'table table-hover table-bordered table-striped',
            'columns' => array(
                array(
                    'column' => 'id',
                    'label' => '#'
                ),

                array(
                    'column' => 'question',
                ),

                array(
                    'column' => 'published',
                    'value' => function($faq){
                        return Element::checkbox(sprintf('published[%s]', $faq->getId()), $faq->getPublished());
                    }
                ),

                array(
                    'column' => 'order',
                    'value' => function($faq){
                        return Element::number(sprintf('order[%s]', $faq->getId()), $faq->getOrder(), array('class' => 'form-control', 'min' => '0'));
                    }
                )
            ),

            'actions' => array(
                'edit' => function($faq){
                    return Icon::edit(
                        $this->url('Faq:Admin:Faq@editAction', $faq->getId()),
                        $this->translate('Edit this pair')
                    );
                },

                'remove' => function($faq){
                    return Icon::remove(
                        $this->url('Faq:Admin:Faq@deleteAction', $faq->getId()),
                        $this->translate('Remove this pair')
                    );
                }
            )
        ))); ?>

        <?php if (empty($faqs)): ?>
        <div class="center-block">
            <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No faqs'); ?></h2>
        </div>
        <?php endif; ?>

        <?php $this->loadPartial('paginator'); ?>    
    </form>
</div>

<div class="card">
    <h3><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Categories'); ?> <small>(<?php echo count($categories); ?>)</small></h3>

    <?= $this->widget(new GridViewWidget($categories, array(
        'tableClass' => 'table table-hover table-bordered table-striped',
        'rowAttributes' => array(
            'class' => function($category) use ($categoryId){
                return $category->getId() == $categoryId ? 'table-info' : null;
            }
        ),

        'columns' => array(
            array(
                'column' => 'id',
                'label' => '#'
            ),

            array(
                'column' => 'name',
                'value' => function($category){
                    $url = $this->mapUrl('Faq:Admin:Faq@categoryAction', array($category->getId()), 0);
                    return Element::link($category->getName(), $url);
                }
            ),

            array(
                'column' => 'order'
            )
        ),

        'actions' => array(
            'edit' => function($faq){
                return Icon::edit(
                    $this->url('Faq:Admin:Category@editAction', $faq->getId()),
                    $this->translate('Edit this category')
                );
            },

            'remove' => function($faq){
                return Icon::remove(
                    $this->url('Faq:Admin:Category@deleteAction', $faq->getId()),
                    $this->translate('Remove this category')
                );
            }
        )
    ))); ?>

    <?php if (empty($categories)): ?>
    <div class="center-block">
        <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No categories'); ?></h2>
    </div>
    <?php endif; ?>
</div>
