<?php

use Krystal\Form\Element;
use Krystal\Grid\Grid;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="btn-toolbar">
	<div class="btn-group">
	  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
		<i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?> <span class="caret"></span>
	  </button>
	  <ul class="dropdown-menu">
         <li><a href="<?php echo $this->url('Faq:Admin:Faq@addAction'); ?>"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Add new FAQ'); ?></a></li>
		 <li><a href="<?php echo $this->url('Faq:Admin:Category@addAction'); ?>"><i class="glyphicon glyphicon-folder-open"></i> <?php $this->show('Add a category'); ?></a></li>
		 <li class="divider"></li>
		 <li class="dropdown-header"><?php $this->show('Actions'); ?></li>

		 <?php if (!empty($faqs)): ?>
		 
		 <li><a href="#" data-button="save-changes" data-url="<?php echo $this->url('Faq:Admin:Faq@tweakAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li><a href="#" data-button="remove-selected" data-url="<?php echo $this->url('Faq:Admin:Faq@deleteAction', null); ?>"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 <?php else: ?>
		 
		 <li class="disabled"><a><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li class="disabled"><a><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 
		 <?php endif; ?>
	  </ul>
	</div>
</div>


<form>
    <div class="row">
        <div class="col-lg-8">
            <?php $this->loadPartial('items-per-page', array('caption' => 'FAQ')); ?>

            <?= Grid::render($faqs, array(
                'batch' => true,
                'pk' => 'id',
                'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
                'columns' => array(
                    array(
                        'column' => 'id',
                        'label' => '#'
                    ),

                    array(
                        'column' => 'question',
                    ),

                    array(
                        'column' => 'published',
                        'value' => function($faq){
                            return Element::checkbox(sprintf('published[%s]', $faq->getId()), $faq->getPublished());
                        }
                    ),

                    array(
                        'column' => 'order',
                        'value' => function($faq){
                            return Element::number(sprintf('order[%s]', $faq->getId()), $faq->getOrder(), array('class' => 'form-control', 'min' => '0'));
                        }
                    )
                ),

                'actions' => array(
                    'edit' => function($faq){
                        return Icon::edit(
                            $this->url('Faq:Admin:Faq@editAction', $faq->getId()),
                            $this->translate('Edit this pair')
                        );
                    },

                    'remove' => function($faq){
                        return Icon::remove(
                            $this->url('Faq:Admin:Faq@deleteAction', $faq->getId()),
                            $this->translate('Remove this pair')
                        );
                    }
                )

            ), $this->translator); ?>

            <?php if (empty($faqs)): ?>
            <div class="center-block">
                <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No faqs'); ?></h2>
            </div>
            <?php endif; ?>

            <?php $this->loadPartial('paginator'); ?>
        </div>

        <div class="col-lg-4">
            <h3><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Categories'); ?> <small>(<?php echo count($categories); ?>)</small></h3>

            <?= Grid::render($categories, array(
                'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
                'rowAttributes' => array(
                    'class' => function($category) use ($categoryId){
                        return $category->getId() == $categoryId ? 'info' : null;
                    }
                ),

                'columns' => array(
                    array(
                        'column' => 'id',
                        'label' => '#'
                    ),

                    array(
                        'column' => 'name',
                        'value' => function($category){
                            $url = $this->mapUrl('Faq:Admin:Faq@categoryAction', array($category->getId()), 0);
                            return Element::link($category->getName(), $url);
                        }
                    ),

                    array(
                        'column' => 'order'
                    )
                ),

                'actions' => array(
                    'edit' => function($faq){
                        return Icon::edit(
                            $this->url('Faq:Admin:Category@editAction', $faq->getId()),
                            $this->translate('Edit this category')
                        );
                    },

                    'remove' => function($faq){
                        return Icon::remove(
                            $this->url('Faq:Admin:Category@deleteAction', $faq->getId()),
                            $this->translate('Remove this category')
                        );
                    }
                )

            ), $this->translator); ?>

            <?php if (empty($categories)): ?>
            <div class="center-block">
                <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No categories'); ?></h2>
            </div>
            <?php endif; ?>
        </div>
    </div>
</form>
